name: pozos8
description: Gestion de Flotas.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  shared_preferences: ^0.5.10
  provider: ^4.3.2+2
  dio: ^3.0.9
  firebase_core: ^0.5.0
  cloud_firestore: ^0.14.0+2
  toast: ^0.1.5
  maps_launcher: ^1.2.2+1
  url_launcher: ^5.5.2
  geolocator: ^6.0.0+4
  flutter_background_service: ^0.0.1+14
  flutter_phoenix: "^0.1.0"
  flutter_native_splash: ^0.1.9

flutter_native_splash:
  image: assets/splash.png
  color: 2e3842


  

  # audioplayer:

dev_dependencies:
  flutter_test:
    sdk: flutter
  


flutter:
  uses-material-design: true
  assets:
    - assets/


  # image_path: "assets/icon/icon.png"
